"use strict";
(function installShareLinks(){
 const T=window.RadharcTools=window.RadharcTools||{},VALID_PERIODS=new Set(["7","30","90","365","1095","all","custom"]),LIMITS={west:-12.5,south:50,east:-4,north:56.5};
 const activeLayerKeys=()=>Object.keys(layers).filter(key=>map.hasLayer(layers[key]));
 const repeated=(params,key,values)=>values.forEach(value=>params.append(key,value));
 const unitParam=value=>{if(value==null||value==="")return null;const number=Number(value);return Number.isSafeInteger(number)&&number>=1&&number<=10000000?number:null;};
 T.buildShareUrl=function(){const url=new URL(window.location.href);url.search="";url.hash="";const p=url.searchParams;p.set("view","1");const period=document.querySelector("#dateRange")?.value||"365";p.set("period",period);if(smartState.customDates?.start)p.set("from",smartState.customDates.start);if(smartState.customDates?.end)p.set("to",smartState.customDates.end);repeated(p,"decision",smartState.decision);repeated(p,"authority",smartState.authority);repeated(p,"category",smartState.category);if(smartState.residentialOnly)p.set("residential","1");if(smartState.minUnits!=null)p.set("minUnits",String(smartState.minUnits));const b=map.getBounds();p.set("bbox",[b.getWest(),b.getSouth(),b.getEast(),b.getNorth()].map(v=>v.toFixed(5)).join(","));p.set("layers",activeLayerKeys().join(","));const search=document.querySelector("#searchInput")?.value.trim();if(search)p.set("search",search);return url.toString();};
 T.shareDashboardLink=async function(){const url=T.buildShareUrl();try{if(navigator.share){await navigator.share({title:"Radharc Pleanála",text:`Irish planning dashboard view · ${smartSummary()}`,url});T.showMessage("Dashboard view shared.");}else{await T.copyText(url);T.showMessage("Share link copied to the clipboard.");}}catch(error){if(error?.name!=="AbortError"){await T.copyText(url);T.showMessage("Share link copied to the clipboard.");}}};
 T.emailDashboardLink=function(){const url=T.buildShareUrl();T.openEmail("Radharc Pleanála dashboard view",`Here is a filtered Irish planning dashboard view.\n\n${smartSummary()}\n\n${url}`);};
 function safeBounds(value){if(!value)return null;const n=value.split(",").map(Number);if(n.length!==4||n.some(v=>!Number.isFinite(v)))return null;const[w,s,e,north]=n;if(w>=e||s>=north||w<LIMITS.west||s<LIMITS.south||e>LIMITS.east||north>LIMITS.north)return null;return[[s,w],[north,e]];}
 function restoreLayers(value){if(value==null)return;const requested=new Set(value.split(",").filter(key=>Object.hasOwn(layers,key)));Object.entries(layers).forEach(([key,layer])=>{if(requested.has(key)&&!map.hasLayer(layer))layer.addTo(map);if(!requested.has(key)&&map.hasLayer(layer))map.removeLayer(layer);const box=document.querySelector(`#layerToggles input[data-k="${key}"]`);if(box)box.checked=requested.has(key);});}
 function restoreSharedView(){const p=new URLSearchParams(window.location.search);if(p.get("view")!=="1")return;const period=VALID_PERIODS.has(p.get("period"))?p.get("period"):"365";const range=document.querySelector("#dateRange"),startInput=document.querySelector("#customStartDate"),endInput=document.querySelector("#customEndDate"),dateStatus=document.querySelector("#customDateStatus");if(period==="custom"){const start=/^\d{4}-\d{2}-\d{2}$/.test(p.get("from")||"")?p.get("from"):"",end=/^\d{4}-\d{2}-\d{2}$/.test(p.get("to")||"")?p.get("to"):"";if(start||end){smartState.customDates={start,end};if(range)range.value="custom";if(startInput)startInput.value=start;if(endInput)endInput.value=end;if(dateStatus)dateStatus.textContent=`Shared period: ${smartPeriodLabel()}.`;}}else{smartState.customDates=null;smartState.lastPreset=period;if(range)range.value=period;if(startInput)startInput.value="";if(endInput)endInput.value="";if(dateStatus)dateStatus.textContent=`Shared period: ${periodLabel()}.`;}
 smartState.decision=[...new Set(p.getAll("decision").filter(Boolean))];smartState.authority=[...new Set(p.getAll("authority").filter(Boolean))];smartState.category=[...new Set(p.getAll("category").filter(Boolean))];["decision","authority","category"].forEach(smartSyncSelect);smartState.residentialOnly=p.get("residential")==="1";smartState.minUnits=unitParam(p.get("minUnits"));window.RadharcResidentialUnits?.syncUi();const search=p.get("search")||"",input=document.querySelector("#searchInput");if(input)input.value=search;restoreLayers(p.get("layers"));const bounds=safeBounds(p.get("bbox"));if(bounds)map.fitBounds(bounds,{animate:false});smartApplyLayerFilters();smartUpdateSummary();const searchStatus=document.querySelector("#searchStatus");if(searchStatus)searchStatus.textContent=search?"Shared search restored. Press Search to list matching records.":"Shared dashboard view restored. Press Search to list records.";update();T.showMessage("Shared dashboard view restored.");}
 T.onReady(restoreSharedView);
})();